version: '3.9'

services:
  addresses-prod:
    image: mysql-addresses-prod:0.1
    build: 
      dockerfile: .docker/mysql/Dockerfile
      context: .
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_HOST
      - MYSQL_DATABASE
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD-SHELL", "/usr/bin/mysql --user=$MYSQL_USER --password=$MYSQL_PASSWORD --execute 'SHOW DATABASES';"]
      interval: 3s
      timeout: 2s
      retries: 5
      start_period: 3s

  express-app-prod:
    image: node-express-app-prod:0.1
    build:
      dockerfile: .docker/express-app/Dockerfile
      context: .
    environment:
      - APP_PORT
    ports:
      - 9000:9000
    depends_on:
      addresses-prod:
        condition: service_healthy
