## ----------------------- TEST RUNNER START ------------------------

# Use this image to build from TS to JS
FROM node:current-alpine AS test_runner

# Default directory within the container
WORKDIR /app

RUN apk -U upgrade && apk add git

# Copy needed files for npm install
COPY package.json package.json
RUN npm install

# Copy over needed files for the build 
COPY tsconfig.json /app/tsconfig.json
COPY jest.config.js /app/jest.config.js
COPY src/ src/

# Execute the build
CMD ["npm", "test"] 

## ----------------------- TEST RUNNER END --------------------------